- name: "Create Backend Directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Installing Node Dependencies"
  become: true
  shell: |
    cd ~/backend-app
    npm install

- name: "Executing node app with pm2 "
  shell: |
    cd ~/backend-app/dist
    pm2 stop default
    pm2 start -f main.js 

  register: execute_node

- name: "print message"
  debug:
    msg: "{{ execute_node_stdout_lines }}"

- name: "configure pm2 to start as a service"
  become: true
  shell: |
   sudo su -c "env PATH=$PATH:/usr/local/bin/ pm2 startup systemd -u ubuntu --hp /home/ubuntu"
   pm2 save 